spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver  
      
# Mybatis配置
mybatis:
    mapperLocations: classpath:com/bao/springboot/mapper/*.xml
    configLocation: classpath:mybatis-config.xml