server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/admin/
      suffix: .jsp
  datasource:
        url: jdbc:mysql://localhost:3306/oldCulture?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
        username: root
        password: root
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters : stat
  http:
    multipart:
      max-file-size: 12MB
      max-request-size: 100MB